' Gambas module file

Public unfocused_hide As Boolean = True
Public UseTray As Boolean = True
Public cleartext As Boolean = True
Public backimage As Image
Public fullyloaded As Boolean = False

Public Function image_from_svg(svg_file As String, rSize As String) As Image
  Dim hSvg As SvgImage
  Dim hImage As Image
  If Not Exist(svg_file, True) Then Return Null
  hSvg = SvgImage.Load(svg_file)
  hImage = New Image(rSize, rSize, Color.Transparent)
  Paint.Begin(hImage)
    hSvg.Resize(rSize, rSize)
    hSvg.Paint
  Paint.End
  Return hImage
End

Public Function Load_image(img_file As String, Optional rSize As Integer = -1) As Image
  Dim i As New Image

  If Not Exist(img_file, True) Then Return Null
  
  If Lower(img_file) Ends ".svg" Then Return image_from_svg(img_file, rSize)
  
  If rSize <> -1 Then 
    i = Image.Load(img_file)
    If i.w <> rSize Then i = i.Stretch(rSize, rSize)
    Return i
  Endif  

  Return Image.Load(img_file)
End

Public Function find_term() As String
  Dim terms As String[] = ["konsole", "gnome-terminal", "xfce4-terminal", "lxterminal", "xterm"]
  Dim term As String
  For Each term In terms
    Debug "checking for " & term & "..."
    If System.Exist(term) Then 
      Debug "found."
      Return System.Find(term)
    Endif
  Next
  Return ""
End

Public Function terminal_cmdline(terminal_emulator As String, cmdline As String) As String
  Return terminal_emulator & " -e " & "\"" & "sh -c ' " & cmdline & "; echo; echo  Press enter to exit ; read ' \""
End

Public Function object_lock(o As Object)
  While Not (Object.IsLocked(o))
    Object.lock(o)
  Wend
End

Public Function object_unlock(o As Object)
  While Object.IsLocked(o)
    Object.unlock(o)
  Wend
End

Public Function IsDesktopFile(sFile As String) As Boolean
  Dim hFile As Stream
  Dim sOneLine As String
  Dim FoundTag As Boolean = False
  Dim maxLines As Integer = 10
  Dim i As Integer = 1
  If Lower(sFile) Ends ".desktop" Then Return True
  Try hFile = Open sFile For Input
  If Error Then Return
  While Not Eof(hFile)
    Line Input #hFile, sOneLine
    sOneLine = Trim(sOneLine)
    If sOneLine = "[Desktop Entry]" Then Return True
    If Not ((sOneLine Begins "#") Or (sOneLine = "")) Then Return False
    i += 1
    If i > maxLines Then Return False
  Wend
  Close #hFile  
  Return False
End
